/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
  GPIO_RegDef_t *pinD = (GPIO_RegDef_t *)GPIOD_BASEADDR;
  RCC_RegDef_t *rcc = (RCC_RegDef_t *)RCC_BASEADDR;

  rcc->AHB1ENR |= (1 << 3);

  pinD->MODER |= (1 << 30);

  pinD->ODR |= (1 << 15);
    /* Loop forever */
	for(;;);
}
